language: cpp

matrix:
    include:
        - name: "Android, Debug"
          os: linux
          dist: bionic
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
              - CTEST_REGEXP="NONE"
        - name: "Android, Release"
          os: linux
          dist: bionic
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
              - CTEST_REGEXP="NONE"
        - name: "Linux, Debug"
          os: linux
          dist: bionic
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-8-cxx17.cmake
              - CTEST_REGEXP="Tests$"
        - name: "Linux, Release"
          os: linux
          dist: bionic
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-8-cxx17.cmake
              - CTEST_REGEXP="Tests$"
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode11.3
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx17.cmake
              - CTEST_REGEXP="Tests$"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode11.3
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx17.cmake
              - CTEST_REGEXP="Tests$"

env:
    global:
        - CTEST_LOG_REGEXP="=== EVENT \#\|SwappedVector\|\[\([a-zA-Z]\+\)\(\/[a-zA-Z0-9]\+\)\?\]"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - unzip
            - wget
            - lcov
            - rpm
            - gcc-8
            - g++-8
        sources:
            - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git
            - lcov

cache:
    directories:
        - $HOME/.hunter

before_install:
    - |
        if [ "$CMAKE_TOOLCHAIN_FILE_NAME" = "android-ndk-r18b-api-21-x86-clang-libcxx.cmake" ]; then
            echo "Installing Android NDK..."
            mkdir -p "$HOME/.android"
            wget -O "$HOME/.android/android-ndk-r18b-linux-x86_64.zip" "https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip"
            unzip -qq "$HOME/.android/android-ndk-r18b-linux-x86_64.zip" -d "$HOME/.android"
            export ANDROID_NDK_r18b="$HOME/.android/android-ndk-r18b"
            ls -la "$ANDROID_NDK_r18b"
        fi

script:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export CC=gcc-8
            export CXX=g++-8
        fi
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

after_success:
    - |
        if [ "$CMAKE_TOOLCHAIN_FILE_NAME" = "android-ndk-r18b-api-21-x86-clang-libcxx.cmake" ]; then
            echo "TODO: Fix and run tests for Android and remove this 'if' statement."
        elif [ "$CMAKE_BUILD_TYPE" = "Release" ]; then
            echo "Code-coverage is only available for debug builds. Skipping..."
        else
            COVERAGE_FILE="$TRAVIS_BUILD_DIR/build/coverage.info"
            echo "coverage.info: $COVERAGE_FILE"
            lcov --capture --directory . --output-file $COVERAGE_FILE
            lcov --remove $COVERAGE_FILE "/Applications/Xcode*" "/usr/*" "*/boost/*" "*/gtest/*" "*/tests/*" "*/_ExternalProjects/*" --output-file $COVERAGE_FILE
            lcov --list $COVERAGE_FILE
            bash <(curl -s https://codecov.io/bash) -f $COVERAGE_FILE || echo "Upload to codecov.io FAILED"
        fi

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "ZZSlwl88DG/cwiDMEVxdsUt7T7WjdBQ9I2K+Be7NL3kt4yRbBpy30rMHwTvDXSSvg/O8bEmnyTRD6TJXP5i9H+cJfoXd/ZK/JfAZKKQ9cnuL0dg88OcN8pkB/QskfchcJm9UzkGI+mJKTrTws9nLqN94oWr4HI8MnaFLQZjZNEumi99FguR+RpbqZB0My3I88Zhw9vyaneBMIwvwE+8LD5otp4WWaiNmvsFfNL/tmyNfwDe0T1K6uds6Rbr+xVRCkUyENNnfd6kGsdElV0HPclZgy20PEB7kxQqbpHnHxY94WdG+IB01Hfr/4Y0YX8QcNUd9QQqbVsj04iSHECBFm7R/kz7YXy/Q76z/SoUXAAApiPEhLWC50CUL5xSoT68EVepNok42TOaZ3itVcPPoNFZppDYeH9/ZwYvkinjZ9VMDNQxK7CWj6RPTaQsRxDZ3pmNOaXcvufuR0qQEKYVBsx4k6dbhP+iQ20KUdNefrwX95Eoy5U5+Hkm/qnCVJv5AkW0qxPplPnjSChIlWErgeqyAOGpoYMmW7XAT/rKHjZYaQ8obsMXYM4ZOQpMCksZNh5Ym+8kH3BP6MqMHaOo4kk8O0FwaJKGThMCB/w4ELjhnjjkec3u0lCZWwvKzMUpn5xRQ6K2kgq99h82Gp4JNJfxhvfeHwoe/h5F4ksU/jtg="
    file: dist/qwertycoin-*
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true
